[project]
name = "agentcore-omnisearch-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "strands-agents>=1.13.0",
    "strands-agents-tools[a2a-client]>=0.2.12",
]

[tool.uv.workspace]
members = ["apps/*"]
