[project]
name = "aws-knowledge-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bedrock-agentcore>=1.0.4",
    "strands-agents-tools>=0.2.12",
    "strands-agents[a2a]>=1.13.0",
]
